display_name: Hiddify Next
publisher_display_name: Hiddify
identity_name: app.hiddify.com
msix_version: 1.0.0.0
logo_path:  windows\runner\resources\app_icon.ico
capabilities: internetClient, privateNetworkClientServer