targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      slang_build_runner:
        options:
          base_locale: en
          input_directory: assets/translations
          input_file_pattern: .i18n.json
          output_directory: lib/gen
          output_file_name: translations.g.dart
          translation_class_visibility: public
          locale_handling: false
